import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/footer/footer";
import { Header } from "@/components/header/header";
import { Providers } from "@/store/providers";

const geistSans = Lato({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} antialiased`}>
                <Providers>
                    <div className="min-h-screen flex justify-between flex-col">
                        <div>
                            <Header />
                            <div>{children}</div>
                        </div>
                        <Footer />
                    </div>
                </Providers>
            </body>
        </html>
    );
}
